package com.product_management.product_management.entity;

import java.time.LocalDate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

/**
 * This class represents a product entity with attributes productId,
 * productName, and createdOn.
 * It is annotated with JPA annotations to map it to a database table named
 * "product_table".
 * @author PUSHKAR D
 * @since 1.0
 */
@Entity
@Data
@Table(name = "product_table")
public class Product {
    /**
     * The unique identifier for each product.
     * It is auto-generated by the database and annotated with JPA annotations.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "productId")
    @NotNull
    private Integer productId;

    /**
     * The name of the product.
     * It is a string and annotated with JPA annotations to map it to the
     * "productName" column in the database.
     */
    @Column(name = "productName")
    private String productName;

    /**
     * The date when the product was created.
     * It is a LocalDate object and annotated with JPA annotations to map it to the
     * "createdOn" column in the database.
     */
    @Column(name = "createdOn")
    private LocalDate createdOn;
}
